### ISSUE TITLE
LUL

### ISSUE THREAD

**Issue by ArconWell** [ArtemOnigiri/webShader#1]
Выглядит круто, но я успел посмотреть только пару кадров и мой браузер крашнулся :D

**Comment by ArtemOnigiri** [comment]
У многих почему-то крашится даже на норм компах, пока не знаю, с чем это связано

**Comment by ArtemOnigiri** [comment]
Поменял немного, может помочь, но это не точно

**Comment by ArconWell** [comment]
Больше не крашится
